# Generated by Django 4.1.1 on 2022-12-26 01:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('patente_vehiculo', models.CharField(max_length=30)),
                ('hora_ingreso', models.TimeField()),
                ('hora_salida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_estacionamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipovehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_segmento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Calzo',
            fields=[
                ('numero_estacionamiento', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
                ('nivel_estacionamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.nivel_estacionamiento')),
                ('tipo_vehiculo', models.ManyToManyField(to='core.tipovehiculo')),
            ],
        ),
    ]
