# Generated by Django 4.1.1 on 2022-12-26 02:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_nivel_estacionamiento_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='calzo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
